import { Restaurant } from '../types';

export const RESTAURANTS: Restaurant[] = [
  {
    id: '1',
    name: 'The Burger Joint',
    cuisine: ['American', 'Burgers'],
    rating: 4.5,
    deliveryTime: 25,
    minOrder: 15,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTW4MXXsRTNPVdBxibCPhan-eebsiP-nOZmUQ&s',
    featured: true,
    // {menus}
   menu: [
  {
    id: 'm1',
    name: 'Classic Cheeseburger',
    description: 'Juicy beef patty with melted cheddar cheese',
    price: 12.99,
    category: 'Main',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlNQ2KlqoI-Y1pziuCN5uhV7SvxLuX5nSdFQ&s',
    isVeg: false,
  },
  {
    id: 'm2',
    name: 'Double Cheese Burger',
    description: 'Two beef patties with double cheese',
    price: 14.99,
    category: 'Main',
    image: 'https://cdn.uengage.io/uploads/29124/image-1639-1766993205.jpg',
    isVeg: false,
  },
  {
    id: 'm3',
    name: 'BBQ Bacon Burger',
    description: 'Smoky BBQ sauce with crispy bacon',
    price: 35.2,
    category: 'Main',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRe4NehledkoNTv8XzV4RAMg67rGNpQSLOanw&s',
    isVeg: false,
  },
  {
    id: 'm4',
    name: 'Chicken Grilled Burger',
    description: 'Grilled chicken patty with lettuce and mayo',
    price: 11.99,
    category: 'Main',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQ1XGR6ME6c4atLJhw_y4A5Pd4aoiOZdYbAg&s',
    isVeg: false,
  },],
  },

  {
    id: '2',
    name: 'Sushi Zen',
    cuisine: ['Japanese', 'Sushi', 'Healthy'],
    rating: 4.8,
    deliveryTime: 40,
    minOrder: 30,
    image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/06/7f/2a/eb/sushi-zen.jpg?w=900&h=500&s=1',
   menu: [
  {
    id: 'm1',
    name: 'Grilled Veg Bowl',
    description: 'Grilled seasonal vegetables with brown rice',
    price: 9.99,
    category: 'Healthy',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjdD6dhKMiD4ZmVMXlq5Uv38wXZaHi3dRKnA&s',
    isVeg: true,
  },
  {
    id: 'm2',
    name: 'Quinoa Salad',
    description: 'Quinoa with fresh veggies and lemon dressing',
    price: 8.99,
    category: 'Healthy',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjtDP2gHqV54tadyYEb2k4Irv1fyh5DuKjsg&s',
    isVeg: true,
  },
  {
    id: 'm3',
    name: 'Avocado Toast',
    description: 'Whole grain toast topped with mashed avocado',
    price: 6.99,
    category: 'Healthy',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1vfxlZV0TT7TF322HUufbRqbioeEKRnO_xQ&s',
    isVeg: true,
  },
  {
    id: 'm4',
    name: 'Fruit Power Bowl',
    description: 'Seasonal fruits with nuts and seeds',
    price: 7.49,
    category: 'Healthy',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs8_ugYRN-QA5YYdxCqsXhY6CeywKdeq2ivA&s',
    isVeg: true,
  },
],
  },

  {
    id: '3',
    name: 'Pizza Palace',
    cuisine: ['Pizza'],
    rating: 4.4,
    deliveryTime: 30,
    minOrder: 20,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdrR8jiUDBFX1-441UYwPHTcTvf5gjnNUD7w&s',
   menu: [
  {
    id: 'm1',
    name: 'Margherita Pizza',
    description: 'Classic tomato sauce with mozzarella and basil',
    price: 9.99,
    category: 'Pizza',
    image: 'https://img.huffingtonpost.com/asset/5aa8034f1e00008e0b7ae8a7.jpeg?cache=UKM6vN10o1&ops=scalefit_500_noupscale',
    isVeg: true,
  },
  {
    id: 'm2',
    name: 'Veg Supreme Pizza',
    description: 'Loaded with onions, capsicum, olives and corn',
    price: 11.99,
    category: 'Pizza',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlqOPiCJCkfPkUZpiPgQm0jCP43u2717neeQ&s',
    isVeg: true,
  },
  {
    id: 'm3',
    name: 'Farmhouse Pizza',
    description: 'Fresh vegetables with rich cheese topping',
    price: 12.49,
    category: 'Pizza',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT47R3J8ptwBG7Cc-UBWcUbLJ4Qy9DdmcgFoA&s',
    isVeg: true,
  },
  {
    id: 'm4',
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni with melted mozzarella',
    price: 13.99,
    category: 'Pizza',
    image: 'https://anotherfoodcritic.wordpress.com/wp-content/uploads/2011/10/cousin-vinnys-pizza-pep-pizza.jpg',
    isVeg: false,
  },
    ],
  },

  {
    id: '4',
    name: 'pasta house',
    cuisine: ['Pasta'],
    rating: 4.6,
    deliveryTime: 35,
    minOrder: 25,
    image: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/02/05/Baked-Feta-Pasta-4_s4x3.jpg.rend.hgtvcom.1280.1280.85.suffix/1615916524567.webp',
    menu: [
       {
    id: 'm8',
    name: 'Veggie Primavera',
    description: 'Mixed vegetables in light tomato sauce',
    price: 10.99,
    category: 'Pasta',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/2022/06/pasta-primavera.jpg',
    isVeg: true,
  },
  {
    id: 'm9',
    name: 'Cheese Baked Pasta',
    description: 'Oven-baked pasta loaded with cheese',
    price: 12.99,
    category: 'Pasta',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScyCnt0CMbyGjKmBC8eMX6ZqP5m1DMDAB4Eg&s',
    isVeg: true,
  },
  {
    id: 'm10',
    name: 'Spinach Corn Pasta',
    description: 'Healthy pasta with spinach and sweet corn',
    price: 10.49,
    category: 'Pasta',
    image: 'https://i.ytimg.com/vi/xYPrEien-Oc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCk_qVZQe-i4HqPBjzePOIwttVyTw',
    isVeg: true,
  },
  {
    id: 'm11',
    name: 'Spicy Garlic Pasta',
    description: 'Garlic-infused pasta with chilli flakes',
    price: 9.99,
    category: 'Pasta',
    image: 'https://i.ytimg.com/vi/I15zAQHdmaY/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLApz4qWw77-qH2bz9_qKg2IP5yZsg',
    isVeg: true,
  },
],
  },

  {
    id: '5',
    name: 'Asian Wok',
    cuisine: ['Asian', 'Chinese', 'Thai'],
    rating: 4.2,
    deliveryTime: 28,
    minOrder: 18,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk9ASPNTHF17Xk_LnT-Ndfsg-bGYrJlQTVYg&s',
    menu: [
  {
    id: 'm6',
    name: 'Veg Hakka Noodles',
    description: 'Stir-fried noodles with fresh vegetables',
    price: 9.99,
    category: 'Chinese',
    image: 'https://myfoodstory.com/wp-content/uploads/2021/02/Vegetable-Hakka-Noodles-Restaurant-Style-3-500x500.jpg',
    isVeg: true,
  },
  {
    id: 'm7',
    name: 'Veg Fried Rice',
    description: 'Wok-tossed rice with mixed vegetables',
    price: 8.99,
    category: 'Chinese',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsLjT0F6yvilCPIn5OXGqm6-crRst-QmzECA&s',
    isVeg: true,
  },
  {
    id: 'm8',
    name: 'Veg Manchurian',
    description: 'Crispy vegetable balls in spicy sauce',
    price: 10.49,
    category: 'Chinese',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyB_4D-eRM8wwiqEnQtOYniAXPjMhO5k1Dfw&s',
    isVeg: true,
  },
  {
    id: 'm9',
    name: 'Chilli Paneer',
    description: 'Paneer cubes tossed in chilli sauce',
    price: 11.99,
    category: 'Chinese',
    image: 'https://spicecravings.com/wp-content/uploads/2022/01/Chilli-Paneer-Featured-2.jpg',
    isVeg: true,
  },
],
  },

  {
    id: '6',
    name: 'Green Bowl',
    cuisine: ['Healthy', 'Salads'],
    rating: 4.7,
    deliveryTime: 20,
    minOrder: 12,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCG3vgVpzU8gcc1AAfNOS7qU6--S_2sNIK-A&s',
    menu: [
      { id: 'm7', name: 'Quinoa Salad', description: 'Protein-rich healthy bowl', price: 8.99, category: 'Salad', image: 'https://picsum.photos/seed/h2/200/200', isVeg: true },
    ],
  },

  {
    id: '7',
    name: 'Sweet Cravings',
    cuisine: ['Burgers', 'Desserts'],
    rating: 4.5,
    deliveryTime: 22,
    minOrder: 10,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvucoerjcTzti0zK5WHKS9sfWw38QaxJ6iEw&s',
    menu: [
      {
    id: 'm5',
    name: 'Crispy Chicken Burger',
    description: 'Fried chicken patty with spicy sauce',
    price: 12.49,
    category: 'Main',
    image: 'https://www.kitchensanctuary.com/wp-content/uploads/2019/08/Crispy-Chicken-Burger-square-FS-4518.jpg',
    isVeg: false,
  },
  {
    id: 'm6',
    name: 'Veggie Burger',
    description: 'Plant-based patty with fresh veggies',
    price: 10.99,
    category: 'Veggie',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQEYb3dHVXt1lAhZ4-e_h5l3207hHDUTV8bAQ&s',
    isVeg: true,
  },
  {
    id: 'm7',
    name: 'Spicy Paneer Burger',
    description: 'Crispy paneer patty with spicy sauce',
    price: 11.49,
    category: 'Veggie',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT05lTMxRxMelNoXKUYHIlVDdlbjiBEDz6Vmg&s',
    isVeg: true,
  },
  {
    id: 'm8',
    name: 'Mushroom Swiss Burger',
    description: 'Sauteed mushrooms with Swiss cheese',
    price: 13.99,
    category: 'Main',
    image: 'https://insanelygoodrecipes.com/wp-content/uploads/2024/08/Mushroom-Swiss-Burger-Featured-500x375.jpg',
    isVeg: false,
  },
],
  },

  {
    id: '8',
    name: 'Roll & Bowl',
    cuisine: ['Asian', 'Sushi'],
    rating: 4.3,
    deliveryTime: 38,
    minOrder: 28,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnGFZlorwqOJaDga42Xx10mG7sHnwrogb1eA&s',
    featured: true,
    menu: [
      {
    id: 'm7',
    name: 'Salmon Nigiri',
    description: 'Fresh salmon over pressed rice',
    price: 10.99,
    category: 'Sushi',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHF9RyJzWnwMTuH18b_C6lt8-Lp9GQlvuTCA&s',
    isVeg: false,
  },
  {
    id: 'm8',
    name: 'Veg Tempura Roll',
    description: 'Crispy tempura vegetables inside a roll',
    price: 8.49,
    category: 'Sushi',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlHg6R_dKehaBlO69qaJBLaj9qqzJxCd9rMw&s',
    isVeg: true,
  },
  {
    id: 'm9',
    name: 'Dragon Roll',
    description: 'Eel and cucumber topped with avocado',
    price: 12.99,
    category: 'Sushi',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR9U-1wrXQ_zf3YAP0PEX5QWPNq9y6Vn2zfw&s',
    isVeg: false,
  },
  {
    id: 'm10',
    name: 'Rainbow Roll',
    description: 'Assorted fish over a California roll',
    price: 13.49,
    category: 'Sushi',
    image: 'https://static.wixstatic.com/media/596070_606c6d12320d433da323af56c2349ac8~mv2.jpg/v1/fill/w_1000,h_754,al_c,q_85,usm_0.66_1.00_0.01/596070_606c6d12320d433da323af56c2349ac8~mv2.jpg',
    isVeg: false,
  },
],
  },

  {
    id: '9',
    name: 'Burger Express',
    cuisine: [ 'Fast Food'],
    rating: 4.1,
    deliveryTime: 18,
    minOrder: 14,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIK5whvL8FPoLXyPbMnePCEbpa82X0ZA0rkA&s',
    menu: [
      { id: 'm10', name: 'Chicken Burger', description: 'Grilled chicken patty', price: 9.49, category: 'Main', image: 'https://picsum.photos/seed/bu2/200/200', isVeg: false },
    ],
  },

  {
    id: '10',
    name: 'Bake House',
    cuisine: ['Indian', 'Cafe'],
    rating: 4.6,
    deliveryTime: 20,
    minOrder: 12,
    image: 'https://yennadosa.com/wp-content/uploads/2024/04/yenna-blog1.png',
    featured: true,
   menu: [
  {
    id: 'm11',
    name: 'Butter Naan',
    description: 'Soft naan brushed with butter',
    price: 2.99,
    category: 'Indian',
    image: 'https://fullofplants.com/wp-content/uploads/2023/05/Homemade-Naan-Bread-Restaurant-Style-Vegan-thumb-1-480x270.jpg',
    isVeg: true,
  },
  {
    id: 'm12',
    name: 'Paneer Butter Masala',
    description: 'Creamy tomato gravy with paneer cubes',
    price: 11.99,
    category: 'Indian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ0WaJJjIKPdt_np1witzZWm3RtOLNqDD1Hw&s',
    isVeg: true,
  },
  {
    id: 'm13',
    name: 'Veg Biryani',
    description: 'Aromatic basmati rice with spices and vegetables',
    price: 9.99,
    category: 'Indian',
    image: 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg',
    isVeg: true,
  },
  {
    id: 'm14',
    name: 'Masala Dosa',
    description: 'Crispy dosa stuffed with spiced potato filling',
    price: 6.99,
    category: 'Indian',
    image: 'https://vismaifood.com/storage/app/uploads/public/8b4/19e/427/thumb__700_0_0_0_auto.jpg',
    isVeg: true,
  },
],
  },
  {
  id: '11',
  name: 'Spice Route',
  cuisine: ['Indian', 'Asian'],
  rating: 4.6,
  deliveryTime: 32,
  minOrder: 18,
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz7LaotYpOlvcAXj8SJvGYwrlei-NuFGCiLg&s',
  menu: [
   {
    id: 'm15',
    name: 'Chole Bhature',
    description: 'Spicy chickpea curry with fluffy fried bread',
    price: 8.49,
    category: 'Indian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyta2FEc05FPDkoHtzey9a8nmlgumGb7lDew&s',
    isVeg: true,
  },
  {
    id: 'm16',
    name: 'Idli Sambar',
    description: 'Steamed rice cakes served with sambar and chutney',
    price: 5.49,
    category: 'Indian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRG8BsK4m2TS42suRCvNzitaTNz3Oiq9UXEXQ&s',
    isVeg: true,
  },
  {
    id: 'm17',
    name: 'Aloo Paratha',
    description: 'Stuffed wheat flatbread served with curd',
    price: 4.99,
    category: 'Indian',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Aloo_Paratha_also_known_as_Batatay_Jo_Phulko.jpg/1200px-Aloo_Paratha_also_known_as_Batatay_Jo_Phulko.jpg',
    isVeg: true,
  },
  {
    id: 'm18',
    name: 'Gulab Jamun',
    description: 'Soft milk-solid dumplings soaked in sugar syrup',
    price: 3.99,
    category: 'Indian',
    image: 'https://pipingpotcurry.com/wp-content/uploads/2023/12/Gulab-Jamun-Recipe-Piping-Pot-Curry.jpg',
    isVeg: true,
  },
],
},

{
  id: '12',
  name: 'Dragon Chinese',
  cuisine: ['Chinese', 'Asian'],
  rating: 4.3,
  deliveryTime: 26,
  minOrder: 16,
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgsNDxqU6xcyGsr9KKTaDn4Hm9UU1g2t-Jwg&s',
  menu: [
     {
    id: 'm10',
    name: 'Schezwan Noodles',
    description: 'Spicy noodles with schezwan sauce',
    price: 9.49,
    category: 'Chinese',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCA5Swv1yc0McEmIfxYE0Yj7oxbvcaPZvcsw&s',
    isVeg: true,
  },
  {
    id: 'm11',
    name: 'Veg Spring Rolls',
    description: 'Crispy rolls stuffed with vegetables',
    price: 6.99,
    category: 'Chinese',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgjVBlOKPYOcNfYK8cccuy9BLvS7Y-gK1Jhg&s',
    isVeg: true,
  },
  {
    id: 'm12',
    name: 'Sweet Corn Soup',
    description: 'Hot and comforting corn soup',
    price: 5.99,
    category: 'Soup',
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/sweet-corn-soup-recipe-500x500.jpg',
    isVeg: true,
  },
  {
    id: 'm13',
    name: 'Chilli Garlic Rice',
    description: 'Rice tossed with garlic and chilli',
    price: 8.49,
    category: 'Chinese',
    image: 'https://i0.wp.com/cookingfromheart.com/wp-content/uploads/2020/09/Chilli-Garlic-Fried-Rice-2.jpg?fit=188%2C250&ssl=1',
    isVeg: true,
  },
  ],
},

{
  id: '13',
  name: 'Pasta Corner',
  cuisine: ['Pasta'],
  rating: 4.4,
  deliveryTime: 34,
  minOrder: 20,
  image: 'https://dukaan.b-cdn.net/700x700/webp/media/e775fbb3-217b-4afd-b4f2-b9d7e5e29691.jpg',
  menu: [
    {
    id: 'm8',
    name: 'Veggie Primavera',
    description: 'Mixed vegetables in light tomato sauce',
    price: 10.99,
    category: 'Pasta',
    image: 'https://cdn.loveandlemons.com/wp-content/uploads/2022/06/pasta-primavera.jpg',
    isVeg: true,
  },
  {
    id: 'm9',
    name: 'Cheese Baked Pasta',
    description: 'Oven-baked pasta loaded with cheese',
    price: 12.99,
    category: 'Pasta',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScyCnt0CMbyGjKmBC8eMX6ZqP5m1DMDAB4Eg&s',
    isVeg: true,
  },
  {
    id: 'm10',
    name: 'Spinach Corn Pasta',
    description: 'Healthy pasta with spinach and sweet corn',
    price: 10.49,
    category: 'Pasta',
    image: 'https://i.ytimg.com/vi/xYPrEien-Oc/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCk_qVZQe-i4HqPBjzePOIwttVyTw',
    isVeg: true,
  },
  {
    id: 'm11',
    name: 'Spicy Garlic Pasta',
    description: 'Garlic-infused pasta with chilli flakes',
    price: 9.99,
    category: 'Pasta',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDqlfq3y1Bs87Q5E1Q57fCG9DNCL1Su8E4nw&s',
    isVeg: true,
  },
  ],
},

{
  id: '14',
  name: 'Italian place',
  cuisine: ['Italian'],
  rating: 4.8,
  deliveryTime: 22,
  minOrder: 14,
  image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/3d/49/32/cousin-mario-s-pizzeria.jpg?w=900&h=500&s=1',
  menu: [
  {
    id: 'm15',
    name: 'Spaghetti Carbonara',
    description: 'Classic creamy sauce with parmesan and herbs',
    price: 12.99,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7npD_Db1WhkPP1g_sDA0rIfVv36LsUc4bTA&s',
    isVeg: true,
  },
  {
    id: 'm16',
    name: 'Lasagna Vegetariana',
    description: 'Layered pasta with vegetables and cheese',
    price: 13.99,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAVURndODp4JfN3R2fD-HmMDmalFzoW8Dgag&s',
    isVeg: true,
  },
  {
    id: 'm17',
    name: 'Risotto Funghi',
    description: 'Creamy risotto with mushrooms and herbs',
    price: 11.49,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDBkUZgC_qnU8zTbzKQcfM1tNj989z3QE3NA&s',
    isVeg: true,
  },
  {
    id: 'm18',
    name: 'Penne Arrabbiata',
    description: 'Spicy tomato sauce with garlic and chilli',
    price: 10.99,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlA6HVim_7d53mZ_azN2W6oWWt-lZm46LOXA&s',
    isVeg: true,
  },
  ],
},

{
  id: '15',
  name: 'Pizza Street',
  cuisine: ['Pizza', 'Fast Food'],
  rating: 4.2,
  deliveryTime: 24,
  minOrder: 17,
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUg6YKuscDqKL0dYHTYkRSj_GcBROWuLfg6w&s',
  menu: [
  {
    id: 'm1',
    name: 'Margherita Pizza',
    description: 'Classic tomato sauce with mozzarella and basil',
    price: 9.99,
    category: 'Pizza',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXiUSvVte_goTOElQzp34cUaHYmhtBxs-0rA&s',
    isVeg: true,
  },
  {
    id: 'm2',
    name: 'Veg Supreme Pizza',
    description: 'Loaded with onions, capsicum, olives and corn',
    price: 11.99,
    category: 'Pizza',
    image: 'https://cdn.apartmenttherapy.info/image/upload/f_auto,q_auto:eco,c_fill,g_auto,w_1500,ar_3:2/k%2Farchive%2F96a882a065d714784009abe521fcd5f65092ac90',
    isVeg: true,
  },
  {
    id: 'm3',
    name: 'Farmhouse Pizza',
    description: 'Fresh vegetables with rich cheese topping',
    price: 12.49,
    category: 'Pizza',
    image: 'https://content.instructables.com/FWV/K66E/KA5CW1A8/FWVK66EKA5CW1A8.jpg?auto=webp',
    isVeg: true,
  },
  {
    id: 'm4',
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni with melted mozzarella',
    price: 13.99,
    category: 'Pizza',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD4sXx-3Aey7nIUahSsE0BuPmRhFKEVnqfkw&s',
    isVeg: false,
  },
    ],
},
{
  id: '16',
  name: 'Italiano Delight',
  cuisine: ['Italian'],
  rating: 4.5,
  deliveryTime: 29,
  minOrder: 16,
  image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYJfE6kHNrQVTckVEFuxEiNlBrkItqgsjn8w&s',
  menu: [
    {
    id: 'm19',
    name: 'Fettuccine Alfredo',
    description: 'Rich creamy white sauce pasta',
    price: 12.49,
    category: 'Italian',
    image: 'https://www.tasteofhome.com/wp-content/uploads/2024/10/Chicken-Alfredo_EXPS_TOHVP24_264237_MR_09_26_1.jpg',
    isVeg: true,
  },
  {
    id: 'm20',
    name: 'Bruschetta',
    description: 'Grilled bread topped with tomato and basil',
    price: 6.99,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPJijMaBIdtSXWF8XIz5yb-cbon5Jg6rpEWQ&s',
    isVeg: true,
  },
  {
    id: 'm21',
    name: 'Gnocchi al Pesto',
    description: 'Soft potato dumplings in pesto sauce',
    price: 11.99,
    category: 'Italian',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR46bLtwQ0fMx2sR-o5oAxxbCJ123Ivl-WBhQ&s',
    isVeg: true,
  },
  {
    id: 'm22',
    name: 'Tiramisu',
    description: 'Classic Italian coffee-flavoured dessert',
    price: 7.49,
    category: 'Italian',
    image: 'https://i0.wp.com/mediterraneantaste.com/wp-content/uploads/2023/11/tiramisu-4583.jpg?w=1200&ssl=1',
    isVeg: true,
  },
],
},
];
